name: EKS Runner Test

on: [push]

jobs:
  build:
    runs-on: [self-hosted]
    strategy:
      matrix:
        job: [1, 2, 3, 4, 5]
    steps:
      - run: echo "Job ${{ matrix.job }}"
      - run: sleep 30s
